run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - goconst
    - gocyclo
    - misspell
    - lll
    - nakedret
    - gocritic
    - unconvert
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/globallogicuki/provider-harbor
  govet:
    enable:
      - shadow
    settings:
      printf:
        funcs:
          - (github.com/crossplane/crossplane-runtime/pkg/logging.Logger).Debug
          - (github.com/crossplane/crossplane-runtime/pkg/logging.Logger).Info
          - (github.com/crossplane/crossplane-runtime/pkg/logging.Logger).WithValues
  lll:
    line-length: 140
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: zz_generated\.deepcopy\.go
      linters:
        - lll
    - path: zz_generated\.managed\.go
      linters:
        - lll
    - path: zz_generated\.managedlist\.go
      linters:
        - lll
    - path: _test\.go
      linters:
        - goconst
        - lll
        - prealloc
        - gocyclo

  exclude:
    # Crossplane runtime uses a lot of reflection which golangci-lint
    # doesn't understand
    - "reflect.*never returns"