version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell

issues:
  exclude-rules:
    # Exclude generated files
    - path: zz_generated\.go
      linters:
        - all
    # Exclude generated deep copy files
    - path: zz_generated\.deepcopy\.go
      linters:
        - all