/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ProjectInitParameters struct {
	AutoSbomGeneration *bool `json:"autoSbomGeneration,omitempty" tf:"auto_sbom_generation,omitempty"`

	CveAllowlist []*string `json:"cveAllowlist,omitempty" tf:"cve_allowlist,omitempty"`

	DeploymentSecurity *string `json:"deploymentSecurity,omitempty" tf:"deployment_security,omitempty"`

	EnableContentTrust *bool `json:"enableContentTrust,omitempty" tf:"enable_content_trust,omitempty"`

	EnableContentTrustCosign *bool `json:"enableContentTrustCosign,omitempty" tf:"enable_content_trust_cosign,omitempty"`

	ForceDestroy *bool `json:"forceDestroy,omitempty" tf:"force_destroy,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	// +crossplane:generate:reference:type=github.com/rossigee/provider-harbor/apis/registry/v1alpha1.Registry
	// +crossplane:generate:reference:extractor=github.com/rossigee/provider-harbor/config/common.ExtractRegistryID()
	RegistryID *float64 `json:"registryId,omitempty" tf:"registry_id,omitempty"`

	// Reference to a Registry in registry to populate registryId.
	// +kubebuilder:validation:Optional
	RegistryIDRef *v1.Reference `json:"registryIdRef,omitempty" tf:"-"`

	// Selector for a Registry in registry to populate registryId.
	// +kubebuilder:validation:Optional
	RegistryIDSelector *v1.Selector `json:"registryIdSelector,omitempty" tf:"-"`

	StorageQuota *float64 `json:"storageQuota,omitempty" tf:"storage_quota,omitempty"`

	VulnerabilityScanning *bool `json:"vulnerabilityScanning,omitempty" tf:"vulnerability_scanning,omitempty"`
}

type ProjectObservation struct {
	AutoSbomGeneration *bool `json:"autoSbomGeneration,omitempty" tf:"auto_sbom_generation,omitempty"`

	CveAllowlist []*string `json:"cveAllowlist,omitempty" tf:"cve_allowlist,omitempty"`

	DeploymentSecurity *string `json:"deploymentSecurity,omitempty" tf:"deployment_security,omitempty"`

	EnableContentTrust *bool `json:"enableContentTrust,omitempty" tf:"enable_content_trust,omitempty"`

	EnableContentTrustCosign *bool `json:"enableContentTrustCosign,omitempty" tf:"enable_content_trust_cosign,omitempty"`

	ForceDestroy *bool `json:"forceDestroy,omitempty" tf:"force_destroy,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	RegistryID *float64 `json:"registryId,omitempty" tf:"registry_id,omitempty"`

	StorageQuota *float64 `json:"storageQuota,omitempty" tf:"storage_quota,omitempty"`

	VulnerabilityScanning *bool `json:"vulnerabilityScanning,omitempty" tf:"vulnerability_scanning,omitempty"`
}

type ProjectParameters struct {

	// +kubebuilder:validation:Optional
	AutoSbomGeneration *bool `json:"autoSbomGeneration,omitempty" tf:"auto_sbom_generation,omitempty"`

	// +kubebuilder:validation:Optional
	CveAllowlist []*string `json:"cveAllowlist,omitempty" tf:"cve_allowlist,omitempty"`

	// +kubebuilder:validation:Optional
	DeploymentSecurity *string `json:"deploymentSecurity,omitempty" tf:"deployment_security,omitempty"`

	// +kubebuilder:validation:Optional
	EnableContentTrust *bool `json:"enableContentTrust,omitempty" tf:"enable_content_trust,omitempty"`

	// +kubebuilder:validation:Optional
	EnableContentTrustCosign *bool `json:"enableContentTrustCosign,omitempty" tf:"enable_content_trust_cosign,omitempty"`

	// +kubebuilder:validation:Optional
	ForceDestroy *bool `json:"forceDestroy,omitempty" tf:"force_destroy,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	// +crossplane:generate:reference:type=github.com/rossigee/provider-harbor/apis/registry/v1alpha1.Registry
	// +crossplane:generate:reference:extractor=github.com/rossigee/provider-harbor/config/common.ExtractRegistryID()
	// +kubebuilder:validation:Optional
	RegistryID *float64 `json:"registryId,omitempty" tf:"registry_id,omitempty"`

	// Reference to a Registry in registry to populate registryId.
	// +kubebuilder:validation:Optional
	RegistryIDRef *v1.Reference `json:"registryIdRef,omitempty" tf:"-"`

	// Selector for a Registry in registry to populate registryId.
	// +kubebuilder:validation:Optional
	RegistryIDSelector *v1.Selector `json:"registryIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	StorageQuota *float64 `json:"storageQuota,omitempty" tf:"storage_quota,omitempty"`

	// +kubebuilder:validation:Optional
	VulnerabilityScanning *bool `json:"vulnerabilityScanning,omitempty" tf:"vulnerability_scanning,omitempty"`
}

// ProjectSpec defines the desired state of Project
type ProjectSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectInitParameters `json:"initProvider,omitempty"`
}

// ProjectStatus defines the observed state of Project.
type ProjectStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Project is the Schema for the Projects API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harbor}
type Project struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ProjectSpec   `json:"spec"`
	Status ProjectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectList contains a list of Projects
type ProjectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Project `json:"items"`
}

// Repository type metadata.
var (
	Project_Kind             = "Project"
	Project_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Project_Kind}.String()
	Project_KindAPIVersion   = Project_Kind + "." + CRDGroupVersion.String()
	Project_GroupVersionKind = CRDGroupVersion.WithKind(Project_Kind)
)

func init() {
	SchemeBuilder.Register(&Project{}, &ProjectList{})
}
