/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BannerMessageInitParameters struct {
	Closable *bool `json:"closable,omitempty" tf:"closable,omitempty"`

	FromDate *string `json:"fromDate,omitempty" tf:"from_date,omitempty"`

	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	ToDate *string `json:"toDate,omitempty" tf:"to_date,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type BannerMessageObservation struct {
	Closable *bool `json:"closable,omitempty" tf:"closable,omitempty"`

	FromDate *string `json:"fromDate,omitempty" tf:"from_date,omitempty"`

	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	ToDate *string `json:"toDate,omitempty" tf:"to_date,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type BannerMessageParameters struct {

	// +kubebuilder:validation:Optional
	Closable *bool `json:"closable,omitempty" tf:"closable,omitempty"`

	// +kubebuilder:validation:Optional
	FromDate *string `json:"fromDate,omitempty" tf:"from_date,omitempty"`

	// +kubebuilder:validation:Optional
	Message *string `json:"message" tf:"message,omitempty"`

	// +kubebuilder:validation:Optional
	ToDate *string `json:"toDate,omitempty" tf:"to_date,omitempty"`

	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ConfigSystemInitParameters struct {
	AuditLogForwardEndpoint *string `json:"auditLogForwardEndpoint,omitempty" tf:"audit_log_forward_endpoint,omitempty"`

	BannerMessage []BannerMessageInitParameters `json:"bannerMessage,omitempty" tf:"banner_message,omitempty"`

	ProjectCreationRestriction *string `json:"projectCreationRestriction,omitempty" tf:"project_creation_restriction,omitempty"`

	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	RobotNamePrefix *string `json:"robotNamePrefix,omitempty" tf:"robot_name_prefix,omitempty"`

	RobotTokenExpiration *float64 `json:"robotTokenExpiration,omitempty" tf:"robot_token_expiration,omitempty"`

	ScannerSkipUpdatePulltime *bool `json:"scannerSkipUpdatePulltime,omitempty" tf:"scanner_skip_update_pulltime,omitempty"`

	SkipAuditLogDatabase *bool `json:"skipAuditLogDatabase,omitempty" tf:"skip_audit_log_database,omitempty"`

	StoragePerProject *float64 `json:"storagePerProject,omitempty" tf:"storage_per_project,omitempty"`
}

type ConfigSystemObservation struct {
	AuditLogForwardEndpoint *string `json:"auditLogForwardEndpoint,omitempty" tf:"audit_log_forward_endpoint,omitempty"`

	BannerMessage []BannerMessageObservation `json:"bannerMessage,omitempty" tf:"banner_message,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	ProjectCreationRestriction *string `json:"projectCreationRestriction,omitempty" tf:"project_creation_restriction,omitempty"`

	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	RobotNamePrefix *string `json:"robotNamePrefix,omitempty" tf:"robot_name_prefix,omitempty"`

	RobotTokenExpiration *float64 `json:"robotTokenExpiration,omitempty" tf:"robot_token_expiration,omitempty"`

	ScannerSkipUpdatePulltime *bool `json:"scannerSkipUpdatePulltime,omitempty" tf:"scanner_skip_update_pulltime,omitempty"`

	SkipAuditLogDatabase *bool `json:"skipAuditLogDatabase,omitempty" tf:"skip_audit_log_database,omitempty"`

	StoragePerProject *float64 `json:"storagePerProject,omitempty" tf:"storage_per_project,omitempty"`
}

type ConfigSystemParameters struct {

	// +kubebuilder:validation:Optional
	AuditLogForwardEndpoint *string `json:"auditLogForwardEndpoint,omitempty" tf:"audit_log_forward_endpoint,omitempty"`

	// +kubebuilder:validation:Optional
	BannerMessage []BannerMessageParameters `json:"bannerMessage,omitempty" tf:"banner_message,omitempty"`

	// +kubebuilder:validation:Optional
	ProjectCreationRestriction *string `json:"projectCreationRestriction,omitempty" tf:"project_creation_restriction,omitempty"`

	// +kubebuilder:validation:Optional
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// +kubebuilder:validation:Optional
	RobotNamePrefix *string `json:"robotNamePrefix,omitempty" tf:"robot_name_prefix,omitempty"`

	// +kubebuilder:validation:Optional
	RobotTokenExpiration *float64 `json:"robotTokenExpiration,omitempty" tf:"robot_token_expiration,omitempty"`

	// +kubebuilder:validation:Optional
	ScannerSkipUpdatePulltime *bool `json:"scannerSkipUpdatePulltime,omitempty" tf:"scanner_skip_update_pulltime,omitempty"`

	// +kubebuilder:validation:Optional
	SkipAuditLogDatabase *bool `json:"skipAuditLogDatabase,omitempty" tf:"skip_audit_log_database,omitempty"`

	// +kubebuilder:validation:Optional
	StoragePerProject *float64 `json:"storagePerProject,omitempty" tf:"storage_per_project,omitempty"`
}

// ConfigSystemSpec defines the desired state of ConfigSystem
type ConfigSystemSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ConfigSystemParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConfigSystemInitParameters `json:"initProvider,omitempty"`
}

// ConfigSystemStatus defines the observed state of ConfigSystem.
type ConfigSystemStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConfigSystemObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ConfigSystem is the Schema for the ConfigSystems API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harbor}
type ConfigSystem struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ConfigSystemSpec   `json:"spec"`
	Status            ConfigSystemStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConfigSystemList contains a list of ConfigSystems
type ConfigSystemList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConfigSystem `json:"items"`
}

// Repository type metadata.
var (
	ConfigSystem_Kind             = "ConfigSystem"
	ConfigSystem_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ConfigSystem_Kind}.String()
	ConfigSystem_KindAPIVersion   = ConfigSystem_Kind + "." + CRDGroupVersion.String()
	ConfigSystem_GroupVersionKind = CRDGroupVersion.WithKind(ConfigSystem_Kind)
)

func init() {
	SchemeBuilder.Register(&ConfigSystem{}, &ConfigSystemList{})
}
