/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ConfigAuthInitParameters struct {
	AuthMode *string `json:"authMode,omitempty" tf:"auth_mode,omitempty"`

	LdapBaseDn *string `json:"ldapBaseDn,omitempty" tf:"ldap_base_dn,omitempty"`

	LdapFilter *string `json:"ldapFilter,omitempty" tf:"ldap_filter,omitempty"`

	LdapGroupAdminDn *string `json:"ldapGroupAdminDn,omitempty" tf:"ldap_group_admin_dn,omitempty"`

	LdapGroupBaseDn *string `json:"ldapGroupBaseDn,omitempty" tf:"ldap_group_base_dn,omitempty"`

	LdapGroupFilter *string `json:"ldapGroupFilter,omitempty" tf:"ldap_group_filter,omitempty"`

	LdapGroupGID *string `json:"ldapGroupGid,omitempty" tf:"ldap_group_gid,omitempty"`

	LdapGroupMembership *string `json:"ldapGroupMembership,omitempty" tf:"ldap_group_membership,omitempty"`

	LdapGroupScope *string `json:"ldapGroupScope,omitempty" tf:"ldap_group_scope,omitempty"`

	LdapGroupUID *string `json:"ldapGroupUid,omitempty" tf:"ldap_group_uid,omitempty"`

	LdapScope *string `json:"ldapScope,omitempty" tf:"ldap_scope,omitempty"`

	LdapSearchDn *string `json:"ldapSearchDn,omitempty" tf:"ldap_search_dn,omitempty"`

	LdapSearchPasswordSecretRef *v1.SecretKeySelector `json:"ldapSearchPasswordSecretRef,omitempty" tf:"-"`

	LdapUID *string `json:"ldapUid,omitempty" tf:"ldap_uid,omitempty"`

	LdapURL *string `json:"ldapUrl,omitempty" tf:"ldap_url,omitempty"`

	LdapVerifyCert *bool `json:"ldapVerifyCert,omitempty" tf:"ldap_verify_cert,omitempty"`

	OidcAdminGroup *string `json:"oidcAdminGroup,omitempty" tf:"oidc_admin_group,omitempty"`

	OidcAutoOnboard *bool `json:"oidcAutoOnboard,omitempty" tf:"oidc_auto_onboard,omitempty"`

	OidcClientID *string `json:"oidcClientId,omitempty" tf:"oidc_client_id,omitempty"`

	OidcClientSecretSecretRef *v1.SecretKeySelector `json:"oidcClientSecretSecretRef,omitempty" tf:"-"`

	OidcEndpoint *string `json:"oidcEndpoint,omitempty" tf:"oidc_endpoint,omitempty"`

	OidcGroupFilter *string `json:"oidcGroupFilter,omitempty" tf:"oidc_group_filter,omitempty"`

	OidcGroupsClaim *string `json:"oidcGroupsClaim,omitempty" tf:"oidc_groups_claim,omitempty"`

	OidcName *string `json:"oidcName,omitempty" tf:"oidc_name,omitempty"`

	OidcScope *string `json:"oidcScope,omitempty" tf:"oidc_scope,omitempty"`

	OidcUserClaim *string `json:"oidcUserClaim,omitempty" tf:"oidc_user_claim,omitempty"`

	OidcVerifyCert *bool `json:"oidcVerifyCert,omitempty" tf:"oidc_verify_cert,omitempty"`

	PrimaryAuthMode *bool `json:"primaryAuthMode,omitempty" tf:"primary_auth_mode,omitempty"`
}

type ConfigAuthObservation struct {
	AuthMode *string `json:"authMode,omitempty" tf:"auth_mode,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	LdapBaseDn *string `json:"ldapBaseDn,omitempty" tf:"ldap_base_dn,omitempty"`

	LdapFilter *string `json:"ldapFilter,omitempty" tf:"ldap_filter,omitempty"`

	LdapGroupAdminDn *string `json:"ldapGroupAdminDn,omitempty" tf:"ldap_group_admin_dn,omitempty"`

	LdapGroupBaseDn *string `json:"ldapGroupBaseDn,omitempty" tf:"ldap_group_base_dn,omitempty"`

	LdapGroupFilter *string `json:"ldapGroupFilter,omitempty" tf:"ldap_group_filter,omitempty"`

	LdapGroupGID *string `json:"ldapGroupGid,omitempty" tf:"ldap_group_gid,omitempty"`

	LdapGroupMembership *string `json:"ldapGroupMembership,omitempty" tf:"ldap_group_membership,omitempty"`

	LdapGroupScope *string `json:"ldapGroupScope,omitempty" tf:"ldap_group_scope,omitempty"`

	LdapGroupUID *string `json:"ldapGroupUid,omitempty" tf:"ldap_group_uid,omitempty"`

	LdapScope *string `json:"ldapScope,omitempty" tf:"ldap_scope,omitempty"`

	LdapSearchDn *string `json:"ldapSearchDn,omitempty" tf:"ldap_search_dn,omitempty"`

	LdapUID *string `json:"ldapUid,omitempty" tf:"ldap_uid,omitempty"`

	LdapURL *string `json:"ldapUrl,omitempty" tf:"ldap_url,omitempty"`

	LdapVerifyCert *bool `json:"ldapVerifyCert,omitempty" tf:"ldap_verify_cert,omitempty"`

	OidcAdminGroup *string `json:"oidcAdminGroup,omitempty" tf:"oidc_admin_group,omitempty"`

	OidcAutoOnboard *bool `json:"oidcAutoOnboard,omitempty" tf:"oidc_auto_onboard,omitempty"`

	OidcClientID *string `json:"oidcClientId,omitempty" tf:"oidc_client_id,omitempty"`

	OidcEndpoint *string `json:"oidcEndpoint,omitempty" tf:"oidc_endpoint,omitempty"`

	OidcGroupFilter *string `json:"oidcGroupFilter,omitempty" tf:"oidc_group_filter,omitempty"`

	OidcGroupsClaim *string `json:"oidcGroupsClaim,omitempty" tf:"oidc_groups_claim,omitempty"`

	OidcName *string `json:"oidcName,omitempty" tf:"oidc_name,omitempty"`

	OidcScope *string `json:"oidcScope,omitempty" tf:"oidc_scope,omitempty"`

	OidcUserClaim *string `json:"oidcUserClaim,omitempty" tf:"oidc_user_claim,omitempty"`

	OidcVerifyCert *bool `json:"oidcVerifyCert,omitempty" tf:"oidc_verify_cert,omitempty"`

	PrimaryAuthMode *bool `json:"primaryAuthMode,omitempty" tf:"primary_auth_mode,omitempty"`
}

type ConfigAuthParameters struct {

	// +kubebuilder:validation:Optional
	AuthMode *string `json:"authMode,omitempty" tf:"auth_mode,omitempty"`

	// +kubebuilder:validation:Optional
	LdapBaseDn *string `json:"ldapBaseDn,omitempty" tf:"ldap_base_dn,omitempty"`

	// +kubebuilder:validation:Optional
	LdapFilter *string `json:"ldapFilter,omitempty" tf:"ldap_filter,omitempty"`

	// +kubebuilder:validation:Optional
	LdapGroupAdminDn *string `json:"ldapGroupAdminDn,omitempty" tf:"ldap_group_admin_dn,omitempty"`

	// +kubebuilder:validation:Optional
	LdapGroupBaseDn *string `json:"ldapGroupBaseDn,omitempty" tf:"ldap_group_base_dn,omitempty"`

	// +kubebuilder:validation:Optional
	LdapGroupFilter *string `json:"ldapGroupFilter,omitempty" tf:"ldap_group_filter,omitempty"`

	// +kubebuilder:validation:Optional
	LdapGroupGID *string `json:"ldapGroupGid,omitempty" tf:"ldap_group_gid,omitempty"`

	// +kubebuilder:validation:Optional
	LdapGroupMembership *string `json:"ldapGroupMembership,omitempty" tf:"ldap_group_membership,omitempty"`

	// +kubebuilder:validation:Optional
	LdapGroupScope *string `json:"ldapGroupScope,omitempty" tf:"ldap_group_scope,omitempty"`

	// +kubebuilder:validation:Optional
	LdapGroupUID *string `json:"ldapGroupUid,omitempty" tf:"ldap_group_uid,omitempty"`

	// +kubebuilder:validation:Optional
	LdapScope *string `json:"ldapScope,omitempty" tf:"ldap_scope,omitempty"`

	// +kubebuilder:validation:Optional
	LdapSearchDn *string `json:"ldapSearchDn,omitempty" tf:"ldap_search_dn,omitempty"`

	// +kubebuilder:validation:Optional
	LdapSearchPasswordSecretRef *v1.SecretKeySelector `json:"ldapSearchPasswordSecretRef,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	LdapUID *string `json:"ldapUid,omitempty" tf:"ldap_uid,omitempty"`

	// +kubebuilder:validation:Optional
	LdapURL *string `json:"ldapUrl,omitempty" tf:"ldap_url,omitempty"`

	// +kubebuilder:validation:Optional
	LdapVerifyCert *bool `json:"ldapVerifyCert,omitempty" tf:"ldap_verify_cert,omitempty"`

	// +kubebuilder:validation:Optional
	OidcAdminGroup *string `json:"oidcAdminGroup,omitempty" tf:"oidc_admin_group,omitempty"`

	// +kubebuilder:validation:Optional
	OidcAutoOnboard *bool `json:"oidcAutoOnboard,omitempty" tf:"oidc_auto_onboard,omitempty"`

	// +kubebuilder:validation:Optional
	OidcClientID *string `json:"oidcClientId,omitempty" tf:"oidc_client_id,omitempty"`

	// +kubebuilder:validation:Optional
	OidcClientSecretSecretRef *v1.SecretKeySelector `json:"oidcClientSecretSecretRef,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	OidcEndpoint *string `json:"oidcEndpoint,omitempty" tf:"oidc_endpoint,omitempty"`

	// +kubebuilder:validation:Optional
	OidcGroupFilter *string `json:"oidcGroupFilter,omitempty" tf:"oidc_group_filter,omitempty"`

	// +kubebuilder:validation:Optional
	OidcGroupsClaim *string `json:"oidcGroupsClaim,omitempty" tf:"oidc_groups_claim,omitempty"`

	// +kubebuilder:validation:Optional
	OidcName *string `json:"oidcName,omitempty" tf:"oidc_name,omitempty"`

	// +kubebuilder:validation:Optional
	OidcScope *string `json:"oidcScope,omitempty" tf:"oidc_scope,omitempty"`

	// +kubebuilder:validation:Optional
	OidcUserClaim *string `json:"oidcUserClaim,omitempty" tf:"oidc_user_claim,omitempty"`

	// +kubebuilder:validation:Optional
	OidcVerifyCert *bool `json:"oidcVerifyCert,omitempty" tf:"oidc_verify_cert,omitempty"`

	// +kubebuilder:validation:Optional
	PrimaryAuthMode *bool `json:"primaryAuthMode,omitempty" tf:"primary_auth_mode,omitempty"`
}

// ConfigAuthSpec defines the desired state of ConfigAuth
type ConfigAuthSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ConfigAuthParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConfigAuthInitParameters `json:"initProvider,omitempty"`
}

// ConfigAuthStatus defines the observed state of ConfigAuth.
type ConfigAuthStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConfigAuthObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ConfigAuth is the Schema for the ConfigAuths API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,harbor}
type ConfigAuth struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authMode) || (has(self.initProvider) && has(self.initProvider.authMode))",message="spec.forProvider.authMode is a required parameter"
	Spec   ConfigAuthSpec   `json:"spec"`
	Status ConfigAuthStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConfigAuthList contains a list of ConfigAuths
type ConfigAuthList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConfigAuth `json:"items"`
}

// Repository type metadata.
var (
	ConfigAuth_Kind             = "ConfigAuth"
	ConfigAuth_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ConfigAuth_Kind}.String()
	ConfigAuth_KindAPIVersion   = ConfigAuth_Kind + "." + CRDGroupVersion.String()
	ConfigAuth_GroupVersionKind = CRDGroupVersion.WithKind(ConfigAuth_Kind)
)

func init() {
	SchemeBuilder.Register(&ConfigAuth{}, &ConfigAuthList{})
}
