//go:build !ignore_autogenerated

/*
Copyright 2024 Crossplane Harbor Provider.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemInfo) DeepCopyInto(out *SystemInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemInfo.
func (in *SystemInfo) DeepCopy() *SystemInfo {
	if in == nil {
		return nil
	}
	out := new(SystemInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemInfoList) DeepCopyInto(out *SystemInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SystemInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemInfoList.
func (in *SystemInfoList) DeepCopy() *SystemInfoList {
	if in == nil {
		return nil
	}
	out := new(SystemInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemInfoObservation) DeepCopyInto(out *SystemInfoObservation) {
	*out = *in
	if in.HarborVersion != nil {
		in, out := &in.HarborVersion, &out.HarborVersion
		*out = new(string)
		**out = **in
	}
	if in.RegistryStorageProviderName != nil {
		in, out := &in.RegistryStorageProviderName, &out.RegistryStorageProviderName
		*out = new(string)
		**out = **in
	}
	if in.DatabaseType != nil {
		in, out := &in.DatabaseType, &out.DatabaseType
		*out = new(string)
		**out = **in
	}
	if in.AuthMode != nil {
		in, out := &in.AuthMode, &out.AuthMode
		*out = new(string)
		**out = **in
	}
	if in.SelfRegistration != nil {
		in, out := &in.SelfRegistration, &out.SelfRegistration
		*out = new(bool)
		**out = **in
	}
	if in.HasCARoot != nil {
		in, out := &in.HasCARoot, &out.HasCARoot
		*out = new(bool)
		**out = **in
	}
	if in.CertificateExpiration != nil {
		in, out := &in.CertificateExpiration, &out.CertificateExpiration
		*out = new(int64)
		**out = **in
	}
	if in.NotaryEnabled != nil {
		in, out := &in.NotaryEnabled, &out.NotaryEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TraceEnabled != nil {
		in, out := &in.TraceEnabled, &out.TraceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemInfoObservation.
func (in *SystemInfoObservation) DeepCopy() *SystemInfoObservation {
	if in == nil {
		return nil
	}
	out := new(SystemInfoObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemInfoParameters) DeepCopyInto(out *SystemInfoParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemInfoParameters.
func (in *SystemInfoParameters) DeepCopy() *SystemInfoParameters {
	if in == nil {
		return nil
	}
	out := new(SystemInfoParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemInfoSpec) DeepCopyInto(out *SystemInfoSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemInfoSpec.
func (in *SystemInfoSpec) DeepCopy() *SystemInfoSpec {
	if in == nil {
		return nil
	}
	out := new(SystemInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemInfoStatus) DeepCopyInto(out *SystemInfoStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemInfoStatus.
func (in *SystemInfoStatus) DeepCopy() *SystemInfoStatus {
	if in == nil {
		return nil
	}
	out := new(SystemInfoStatus)
	in.DeepCopyInto(out)
	return out
}
