apiVersion: harbor.m.crossplane.io/v1beta1
kind: Project
metadata:
  name: uptest-member-proj
  namespace: uptest
  annotations:
    meta.upbound.io/example-id: harbor/v1beta1/project
spec:
  forProvider:
    name: uptest-member-proj
    public: false
  providerConfigRef:
    kind: ProviderConfig
    name: harbor-e2e
---
apiVersion: harbor.m.crossplane.io/v1beta1
kind: Member
metadata:
  name: uptest-member
  namespace: uptest
  annotations:
    meta.upbound.io/example-id: harbor/v1beta1/member
spec:
  forProvider:
    projectId: uptest-member-proj
    type: user
    username: uptest-user
    role: developer
  providerConfigRef:
    kind: ProviderConfig
    name: harbor-e2e
