apiVersion: project.harbor.m.crossplane.io/v1beta1
kind: Project
metadata:
  name: uptest-usermember-proj
  namespace: uptest
  annotations:
    meta.upbound.io/example-id: harbor/v1beta1/usermember
spec:
  forProvider:
    name: uptest-usermember-proj
    public: false
  providerConfigRef:
    kind: ProviderConfig
    name: harbor-e2e
---
apiVersion: member.harbor.m.crossplane.io/v1beta1
kind: UserMember
metadata:
  name: uptest-usermember
  namespace: uptest
  annotations:
    meta.upbound.io/example-id: harbor/v1beta1/usermember
spec:
  forProvider:
    projectId: uptest-usermember-proj
    username: uptest-user
    role: developer
  providerConfigRef:
    kind: ProviderConfig
    name: harbor-e2e
