apiVersion: project.harbor.m.crossplane.io/v1beta1
kind: Project
metadata:
  name: uptest-webhook-proj
  namespace: uptest
  annotations:
    meta.upbound.io/example-id: harbor/v1beta1/project
spec:
  forProvider:
    name: uptest-webhook-proj
    public: false
  providerConfigRef:
    kind: ProviderConfig
    name: harbor-e2e
---
apiVersion: webhook.harbor.m.crossplane.io/v1beta1
kind: Webhook
metadata:
  name: uptest-webhook
  namespace: uptest
  annotations:
    meta.upbound.io/example-id: harbor/v1beta1/webhook
spec:
  forProvider:
    name: uptest-webhook
    projectId: uptest-webhook-proj
    url: https://example.com/hook
    eventTypes: ["PUSH_ARTIFACT"]
    enabled: true
    skipCertVerify: true
  providerConfigRef:
    kind: ProviderConfig
    name: harbor-e2e
